# Extract backup data

---

- name: Assert that at least one borgmatic extract item is defined
  ansible.builtin.assert:
    that:
      - borgmatic_extract[0].repository is defined
      - borgmatic_extract[0].destination is defined
    fail_msg: Must define at least one borgmatic extract in borgmatic_extract

- name: Extract backup data
  ansible.builtin.command: >
    borgmatic extract
    --repository {{ item.repository }}
    --archive {{ item.archive | default('latest') }}
    {% if item.paths is defined %}
      --path{% for path in item.paths %} {{ path.lstrip('/') }}{% endfor %}
    {% endif %}
    --destination {{ item.destination }}
  changed_when: true
  become_user: '{{ borgmatic_user_facts.name }}'
  become: true
  loop: '{{ borgmatic_extract }}'
