# Handlers

---

- name: Ensure borgmatic services are configured
  include_tasks: configure-services.yml
  when: borgmatic_configure_services

- name: Ensure absent borgmatic services are removed
  include_tasks: cleanup-services.yml
  when: borgmatic_configure_services
